# 🚀 Enhanced Starship Configuration
# Optimized for modern development workflows with WSL support
# Last updated: July 4, 2025

# Main prompt format with enhanced modules
format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$cpp\
$python\
$nodejs\
$rust\
$golang\
$java\
$kotlin\
$scala\
$php\
$ruby\
$elixir\
$elm\
$haskell\
$julia\
$nim\
$gradle\
$dotnet\
$lua\
$zig\
$dart\
$swift\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
$terraform\
[](fg:#06969A bg:#33658A)\
$memory_usage\
$cmd_duration\
[](fg:#33658A)\
$line_break\
$character\
"""

# Right prompt for additional info
right_format = """
$shell\
$status\
$jobs\
"""

# Clean prompt start
add_newline = false

# Continuation prompt
continuation_prompt = "▶▶ "

# ===============================================================================
# CORE MODULES
# ===============================================================================

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[username]
show_always = true
style_user = "bg:#9A348E bold"
style_root = "bg:#9A348E bold red"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = false
symbols.Windows = "󰍲 "
symbols.Ubuntu = " "
symbols.Linux = "󰌽 "
symbols.Arch = " "
symbols.Debian = " "
symbols.Fedora = " "
symbols.Alpine = " "
symbols.Macos = "󰀵 "

[directory]
style = "bg:#DA627D bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "󰌾"
home_symbol = "󰋜"

[directory.substitutions]
"Documents" = "󰈙 Docs"
"Downloads" = "󰇚 Downloads"
"Music" = "󰝚 Music"
"Pictures" = "󰉏 Pics"
"Videos" = "󰕧 Videos"
"Desktop" = "󰇄 Desktop"
"projects" = "󰲋 Projects"
"work" = "󱔟 Work"
"dotfiles" = "󰙵 Dotfiles"
"repositories" = "󰊢 Repos"
"notes" = "󰠮 Notes"

# ===============================================================================
# GIT CONFIGURATION
# ===============================================================================

[git_branch]
symbol = "󰘬 "
style = "bg:#FCA17D bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "󰞇 "
ahead = "󰜷 "
behind = "󰜮 "
diverged = "󰹺 "
up_to_date = "󰚰 "
untracked = "󰋖 "
stashed = "󰏗 "
modified = "󰏫 "
staged = "󰐗 "
renamed = "󰑕 "
deleted = "󰍶 "

[git_metrics]
added_style = "bg:#FCA17D green"
deleted_style = "bg:#FCA17D red"
format = '([+$added ]($added_style)[-$deleted]($deleted_style))'
disabled = false

[git_commit]
commit_hash_length = 7
style = "bg:#FCA17D"
format = '[ $hash$tag ]($style)'

# ===============================================================================
# PROGRAMMING LANGUAGES
# ===============================================================================

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[python]
symbol = "󰌠 "
style = "bg:#86BBD8"
format = '[ $symbol($version)( $virtualenv) ]($style)'
pyenv_version_name = true
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile"]

[nodejs]
symbol = "󰎙 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'
detect_files = ["package.json", ".nvmrc", "tsconfig.json"]
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]

# TypeScript detection is handled by nodejs module
# [typescript] module doesn't exist in Starship

[rust]
symbol = "󱘗 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = "󰟓 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[java]
symbol = "󰬷 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[kotlin]
symbol = "󱈙 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[php]
symbol = "󰌟 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[ruby]
symbol = "󰴭 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[lua]
symbol = "󰢱 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[zig]
symbol = "󰰦 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[dart]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[swift]
symbol = "󰛥 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[dotnet]
symbol = "󰪮 "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

# ===============================================================================
# BUILD TOOLS
# ===============================================================================

[gradle]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

# Maven is not a standalone module - it's detected by gradle or other build tools
# [maven] module doesn't exist in Starship

# ===============================================================================
# CONTAINERIZATION & CLOUD
# ===============================================================================

[docker_context]
symbol = "󰡨 "
style = "bg:#06969A"
format = '[ $symbol$context ]($style)'

[kubernetes]
symbol = "󱃾 "
style = "bg:#06969A"
format = '[ $symbol$context( $namespace) ]($style)'
disabled = false

[aws]
symbol = "󰸏 "
style = "bg:#06969A"
format = '[ $symbol($profile)( $region) ]($style)'
disabled = false

[gcloud]
symbol = "󱇶 "
style = "bg:#06969A"
format = '[ $symbol($project) ]($style)'
disabled = false

[azure]
symbol = "󰠅 "
style = "bg:#06969A"
format = '[ $symbol($subscription) ]($style)'
disabled = false

[terraform]
symbol = "󱁢 "
style = "bg:#06969A"
format = '[ $symbol$workspace ]($style)'
disabled = false

# ===============================================================================
# SYSTEM MONITORING
# ===============================================================================

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
format = '[ $symbol$percentage ]($style)'

[[battery.display]]
threshold = 15
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 100
style = "bg:#33658A"

[memory_usage]
symbol = "󰍛 "
style = "bg:#33658A"
format = '[ $symbol${ram}( | ${swap}) ]($style)'
threshold = 70
disabled = false

[cmd_duration]
min_time = 2000
style = "bg:#33658A"
format = '[ 󰔛 $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A bold"
format = '[ 󰥔 $time ]($style)'

# ===============================================================================
# SHELL & STATUS
# ===============================================================================

[shell]
bash_indicator = "󱆃 "
zsh_indicator = "󰰶 "
fish_indicator = "󰈺 "
powershell_indicator = "󰨊 "
disabled = false
style = "bold cyan"

[status]
style = "bold red"
symbol = "󰅙 "
success_symbol = "󰸞 "
format = '[$symbol$status]($style)'
disabled = false

[jobs]
symbol = "󰜎 "
style = "bold blue"
number_threshold = 1
format = '[$symbol$number]($style)'
